apiVersion: v1
items:
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    labels:
      app: hello-world-rest-api
    name: hello-world-rest-api
    namespace: default
  spec:
    replicas: 3
    selector:
      matchLabels:
        app: hello-world-rest-api
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        labels:
          app: hello-world-rest-api
      spec:
        containers:
        - image: handesagar/hello-world-rest-api:1.0.3
          imagePullPolicy: IfNotPresent
          name: hello-world-rest-api
        restartPolicy: Always
        terminationGracePeriodSeconds: 30
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: hello-world-rest-api
  name: hello-world-rest-api
  namespace: default
spec:
  ports:
  - nodePort: 31938
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: hello-world-rest-api
  sessionAffinity: None
  type: LoadBalancer  