apiVersion: v1
kind: Service
metadata:
  labels:
    app: hello-world-rest-api
  name: hello-world-rest-api
  namespace: default
spec:
  ports:
  - nodePort: 31938
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: hello-world-rest-api
  sessionAffinity: None
  type: LoadBalancer